import json
import sys
import os
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, Image, KeepTogether, HRFlowable
)
from datetime import datetime

class AfterSubmitStudentDataPDF:
    def __init__(self, student_data, output_filename):
        self.student_data = student_data
        self.output_filename = output_filename
        self.page_width, self.page_height = A4
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
        
    def _setup_custom_styles(self):
        """Setup custom professional paragraph styles"""
        # Main Title - Clean, dark blue, centered
        self.styles.add(ParagraphStyle(
            name='DocTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#003366'), # Dark Blue
            spaceAfter=4,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))
        
        # Subtitle - Grey, lighter
        self.styles.add(ParagraphStyle(
            name='DocSubtitle',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor('#666666'),
            spaceAfter=20,
            alignment=TA_CENTER,
            fontName='Helvetica'
        ))
        
        # Section Header - Modern with bottom border
        self.styles.add(ParagraphStyle(
            name='SectionTitle',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor('#003366'),
            spaceBefore=15,
            spaceAfter=8,
            alignment=TA_LEFT,
            fontName='Helvetica-Bold',
            borderWidth=1,
            borderColor=colors.HexColor('#cccccc'),
            borderPadding=5,
            borderRadius=2
            # We simulate a bottom border line with a drawing or just HR later, 
            # here we use simple text styling
        ))
        
        # Field Label
        self.styles.add(ParagraphStyle(
            name='Label',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.HexColor('#555555'),
            fontName='Helvetica-Bold',
            alignment=TA_LEFT
        ))
        
        # Field Value
        self.styles.add(ParagraphStyle(
            name='Value',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.black,
            fontName='Helvetica',
            alignment=TA_LEFT,
            leading=12
        ))
        
        # Footer text
        self.styles.add(ParagraphStyle(
            name='Footer',
            parent=self.styles['Normal'],
            fontSize=8,
            textColor=colors.HexColor('#999999'),
            alignment=TA_CENTER
        ))

    def _draw_header_footer(self, canvas, doc):
        """Draws header and footer on each page"""
        canvas.saveState()
        
        # Footer
        page_num = canvas.getPageNumber()
        text = "Generated by BMS System | Page %s" % page_num
        canvas.setFont('Helvetica', 8)
        canvas.setFillColor(colors.HexColor('#888888'))
        canvas.drawCentredString(self.page_width/2, 10*mm, text)
        
        canvas.restoreState()

    def generate(self):
        """Generate the complete PDF"""
        doc = SimpleDocTemplate(
            self.output_filename,
            pagesize=A4,
            rightMargin=20*mm, # Slightly larger margins for pro look
            leftMargin=20*mm,
            topMargin=20*mm,
            bottomMargin=25*mm
        )
        
        story = []
        
        # --- Header Section (Logo/Title) ---
        # If you had a logo, you'd place it here. We'll use a text placeholder or just the title.
        story.append(Paragraph("BMS APPLICATION SUMMARY", self.styles['DocTitle']))
        story.append(Paragraph(f"Ref: {self.student_data.get('temp_id', 'N/A')} | Date: {datetime.now().strftime('%Y-%m-%d')}", self.styles['DocSubtitle']))
        story.append(Spacer(1, 5*mm))
        
        # --- QR Code & Photo Enclosure (Corrected) ---
        # Load the BMS logo (prefer local, fallback to web)
        import urllib.request

        logo_path_local = os.path.join('admin', 'uploads', 'company_profiles', 'bmslogo.png')
        logo_path_web = 'https://202.124.164.112:8140/img/logo4.png'

        logo_path = None
        if os.path.exists(logo_path_local):
            logo_path = logo_path_local
        else:
            # Try to download web logo to temp if needed (since reportlab's Image does not handle URLs)
            try:
                import tempfile
                with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp:
                    urllib.request.urlretrieve(logo_path_web, tmp.name)
                    logo_path = tmp.name
            except Exception:
                logo_path = None

        qr_path = self.student_data.get('qr_image_path', self.student_data.get('qr_path', ''))

        images_row = []

        # Logo Flowable (Left)
        if logo_path and os.path.exists(logo_path):
            try:
                img = Image(logo_path, width=40*mm, height=20*mm)
                img.hAlign = 'LEFT'
                images_row.append(img)
            except Exception:
                images_row.append(Spacer(1, 1))
        else:
            images_row.append(Spacer(1, 1))  # Empty slot

        # Center Spacer
        images_row.append(Spacer(1, 1))

        # QR Flowable (Right)
        if qr_path and os.path.exists(qr_path):
            try:
                qr = Image(qr_path, width=35*mm, height=35*mm)
                qr.hAlign = 'RIGHT'
                images_row.append(qr)
            except:
                images_row.append(Spacer(1,1))
        else:
             images_row.append(Spacer(1,1))
             
        # Create a table for the top section: [Logo | (Spacer) | QR]
        # Align: Left | Center | Right
        img_table = Table([images_row], colWidths=[60*mm, 50*mm, 60*mm])
        img_table.setStyle(TableStyle([
            ('ALIGN', (0,0), (0,0), 'LEFT'),      # Col 0: Logo Left
            ('ALIGN', (2,0), (2,0), 'RIGHT'),     # Col 2: QR Right
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'), # Vertically middle
        ]))
        story.append(img_table)
        story.append(Spacer(1, 5*mm))
        
        # --- HR Line ---
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#e0e0e0')))
        story.append(Spacer(1, 10*mm))
        
        # --- Personal Information (2 Column Layout) ---
        story.append(Paragraph("Personal Information", self.styles['SectionTitle']))
        
        data = self.student_data
        
        # Define field-value pairs
        # We'll create a list of list suitable for a table
        
        p_info = [
            ("Full Name:", data.get('fullname', '-')),
            ("Name on Certificate:", data.get('certificate_name', '-')),
            ("Date of Birth:", data.get('dob', '-')),
            ("Gender:", data.get('gender', '-')),
            ("Nationality:", data.get('nationality', '-')),
            ("NIC / Passport:", f"{data.get('nic', '')} / {data.get('passport', '')}".strip(' / ')),
        ]
        
        # Convert to Table Rows (Label | Value)
        # To make it 2 columns, we can do: Label | Value | Label | Value
        # But names are long, so Full Name gets its own row usually.
        
        # Row 1: Full Name (Spans 2 cols visually)
        # Structure: [[L, V], [L, V]...] -> we want a clean look.
        # Let's use a simple 2-col key-value table, but we split the data into two lists and join them? 
        # Easier: Just standard Key-Value rows for long text, 2-col for short.
        
        # Full Name & Cert Name (Long)
        story.append(self._create_kv_table([
            ("Full Name", data.get('fullname', '-')),
            ("Name on Cert.", data.get('certificate_name', '-'))
        ], col_widths=[40*mm, 130*mm]))
        
        # Short fields grid (DOB, Gender, Nationality, NIC)
        # Row 1: DOB | Gender
        # Row 2: Nationality | NIC
        grid_data = [
            [self._lbl("Date of Birth"), self._val(data.get('dob', '-')), self._lbl("Gender"), self._val(data.get('gender', '-'))],
            [self._lbl("Nationality"), self._val(data.get('nationality', '-')), self._lbl("NIC/Passport"), self._val(f"{data.get('nic', '')} {data.get('passport', '')}")]
        ]
        t_grid = Table(grid_data, colWidths=[30*mm, 55*mm, 30*mm, 55*mm])
        t_grid.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('LEFTPADDING', (0,0), (-1,-1), 0),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ]))
        story.append(t_grid)
        
        story.append(Spacer(1, 5*mm))

        # --- Contact Info ---
        story.append(Paragraph("Contact Information", self.styles['SectionTitle']))
        
        # Addresses
        story.append(self._create_kv_table([
            ("Permanent Addr.", data.get('permanent_address', '-')),
            ("Current Addr.", data.get('current_address', '-'))
        ], col_widths=[40*mm, 130*mm]))
        
        # Phones / Email
        grid_contact = [
            [self._lbl("Mobile"), self._val(data.get('mobile', '-')), self._lbl("Home"), self._val(data.get('home_number', '-'))],
            [self._lbl("Office"), self._val(data.get('office_number', '-')), self._lbl("Email"), self._val(data.get('email', '-'))],
            [self._lbl("Emergency"), self._val(data.get('emergency_contact', '-')), "", ""]
        ]
        t_contact = Table(grid_contact, colWidths=[30*mm, 55*mm, 30*mm, 55*mm])
        t_contact.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('LEFTPADDING', (0,0), (-1,-1), 0),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ]))
        story.append(t_contact)
        
        story.append(Spacer(1, 5*mm))

        # --- Programme ---
        story.append(Paragraph("Programme Details", self.styles['SectionTitle']))
        story.append(self._create_kv_table([
            ("Programme", data.get('program', '-')),
            ("Batch", data.get('batch', '-'))
        ], col_widths=[40*mm, 130*mm]))
        
        story.append(Spacer(1, 10*mm))
        
        # --- Page Break possible here if content reduces space, but usually fits on P1. 
        # Let's break for Qualifications to be clean.
        # story.append(PageBreak()) 
        
        # --- Educational Qualifications ---
        story.append(Paragraph("Educational Qualifications", self.styles['SectionTitle']))

        # Data is at root level now (from save_register.php)
        ol_results = data.get('ol_results', [])
        al_results = data.get('al_results', [])
        academic = data.get('academic_qualifications', [])
        other = data.get('other_qualifications', [])

        # O/L Table
        if ol_results:
            story.append(Paragraph("G.C.E. O/L Results", self.styles['Heading3']))
            
            # Header Info (School/Year)
            first_ol = ol_results[0]
            story.append(self._create_kv_table([
                ("School", first_ol.get('school', '-')),
                ("Year", first_ol.get('year', '-'))
            ], col_widths=[30*mm, 140*mm]))
            
            # Subject Table
            headers = ["Subject", "Grade"]
            rows = []
            for item in ol_results:
                rows.append([
                    item.get('subject',''), 
                    item.get('grade','')
                ])
            story.append(self._create_grade_table(headers, rows))
            story.append(Spacer(1, 5*mm))

        # A/L Table
        if al_results:
            story.append(Paragraph("G.C.E. A/L Results", self.styles['Heading3']))
            
            # Header Info (School/Year)
            first_al = al_results[0]
            story.append(self._create_kv_table([
                ("School", first_al.get('school', '-')),
                ("Year", first_al.get('year', '-'))
            ], col_widths=[30*mm, 140*mm]))
            
            # Subject Table
            headers = ["Subject", "Grade"]
            rows = []
            for item in al_results:
                rows.append([
                    item.get('subject',''), 
                    item.get('grade','')
                ])
            story.append(self._create_grade_table(headers, rows))
            story.append(Spacer(1, 5*mm))

        # Academic Table
        if academic:
            story.append(Paragraph("Academic/Professional Qualifications", self.styles['Heading3']))
            headers = ["Qualification", "Institution", "Year"]
            rows = []
            for item in academic:
                rows.append([
                    Paragraph(str(item.get('qualification','')), self.styles['Value']), 
                    Paragraph(str(item.get('institution','')), self.styles['Value']), 
                    Paragraph(str(item.get('year','')), self.styles['Value'])
                ])
            story.append(self._create_data_table(headers, rows, [70*mm, 75*mm, 25*mm]))
            story.append(Spacer(1, 5*mm))

        # Other
        if other:
            story.append(Paragraph("Other Qualifications", self.styles['Heading3']))
            for item in other:
                # Item is a string here
                story.append(Paragraph(f"• {str(item)}", self.styles['Normal']))
            story.append(Spacer(1, 5*mm))

        # Build with footer
        doc.build(story, onFirstPage=self._draw_header_footer, onLaterPages=self._draw_header_footer)

    def _lbl(self, text):
        return Paragraph(text, self.styles['Label'])

    def _val(self, text):
        return Paragraph(str(text), self.styles['Value'])

    def _create_kv_table(self, data_pairs, col_widths):
        """Creates a simple Key-Value table [Label | Value]"""
        table_data = []
        for key, val in data_pairs:
            table_data.append([self._lbl(key), self._val(val)])
        
        t = Table(table_data, colWidths=col_widths)
        t.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('LEFTPADDING', (0,0), (-1,-1), 0),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
            ('GRID', (0,0), (-1,-1), 0.25, colors.HexColor('#e0e0e0')), # Light grid
            ('BACKGROUND', (0,0), (0,-1), colors.HexColor('#f9f9f9')), # Light grey for keys
        ]))
        return t

    def _create_data_table(self, headers, rows, col_widths):
        """Creates a standard data table with blue header"""
        data = [headers] + rows
        t = Table(data, colWidths=col_widths)
        
        style = [
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#003366')), # Dark Blue Header
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,0), 10),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cccccc')),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('TOPPADDING', (0,0), (-1,-1), 6),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ]
        
        # Alternating rows
        for i in range(1, len(data)):
            if i % 2 == 0:
                bg = colors.HexColor('#f0f4f8')
            else:
                bg = colors.white
            style.append(('BACKGROUND', (0,i), (-1,i), bg))
            
        t.setStyle(TableStyle(style))
        return t

    def _create_grade_table(self, headers, rows):
        """Creates a result table with centered Grade column and full width"""
        data = [headers] + rows
        # Full width ~170mm (130+40)
        t = Table(data, colWidths=[130*mm, 40*mm])
        
        style = [
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#003366')), # Dark Blue Header
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,0), 10),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cccccc')),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('TOPPADDING', (0,0), (-1,-1), 6),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
            # Alignments
            ('ALIGN', (0,0), (0,-1), 'LEFT'),   # Subject
            ('ALIGN', (1,0), (1,-1), 'CENTER'), # Grade
        ]
        
        # Alternating rows
        for i in range(1, len(data)):
            if i % 2 == 0:
                bg = colors.HexColor('#f0f4f8')
            else:
                bg = colors.white
            style.append(('BACKGROUND', (0,i), (-1,i), bg))
            
        t.setStyle(TableStyle(style))
        return t

def main():
    if len(sys.argv) < 2:
        print("Usage: python After_submit_student_data.py <json_file>", file=sys.stderr)
        sys.exit(1)
    
    json_file = sys.argv[1]
    try:
        with open(json_file, 'r') as f:
            data = json.load(f)
    except Exception as e:
        print(f"Error loading JSON: {e}", file=sys.stderr)
        sys.exit(1)
        
    output_filename = data.get('output_pdf_path', data.get('output_filename', 'output.pdf'))
    
    try:
        pdf = AfterSubmitStudentDataPDF(data, output_filename)
        pdf.generate()
        print(f"Success: {output_filename}")
    except Exception as e:
        print(f"Error generating PDF: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == '__main__':
    main()
