; DB_HOST = "15.235.229.3"
; DB_NAME = ""
; DB_USER = ""
; DB_PASS = ""

DB_HOST = "localhost"
; DB_NAME = "ims-hosted-updated"
DB_NAME = "ims_new_september"
DB_USER = "root"
DB_PASS = ""




; Base URL for absolute image paths in emails
BASE_URL = "https://ims.bms.ac.lk/"

; SMTP Configuration
SMTP_HOST = "smtp.office365.com"
SMTP_PORT = 587
SMTP_USER = "noreply@bms.ac.lk"
SMTP_PASS = "gqfxxrphvjnlmwrn"
SMTP_FROM_EMAIL = "noreply@bms.ac.lk"
SMTP_FROM_NAME = "Business Management School"
